export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <header style={{ padding: "1rem", backgroundColor: "lightblue" }}>
          <p>This is Header Section</p>
        </header>
        {children}
        <footer style={{ padding: "1rem", backgroundColor: "ghostwhite" }}>
          <p>This is Footer Section</p>
        </footer>
      </body>
    </html>
  );
}
